# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8081
redis:
  host: 192.168.1.51
  port: 7339
markerhub:
  jwt:
    # 加密密钥
    secret: skdlui546adfet46465
    # token有效时长,7天,单位 秒
    expire: 604800
    header: HttpServletRequest